#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults


# param set-default ASPD_SCALE	1
# param set-default ASPD_SCALE_EST	0
# param set-default COM_HOME_H_T	5
# param set-default COM_HOME_V_T	10
# param set-default COM_POS_FS_GAIN	10
# param set-default COM_POS_FS_PROB	30
# param set-default COM_REARM_GRACE	1
# param set-default FW_POSCTL_INV_ST	0

# param set-default RC_ACRO_TH	0.75
# param set-default RC_ASSIST_TH	0.25
# param set-default RC_AUTO_TH	0.75
# param set-default RC_MAN_TH	0.75
# param set-default RC_POSCTL_TH	0.75
# param set-default RC_STAB_TH	0.5
# param set-default RTL_FLT_TIME	15
# param set-default SYS_AUTOCONFIG	0
param set-default COM_RCL_EXCEPT 4
# param set-default COM_FLIGHT_UUID 11
param set-default BAT_N_CELLS 4

param set-default FW_L1_PERIOD 12
param set-default FW_MAN_P_MAX 30
param set-default FW_PR_FF 0.2
param set-default FW_PR_I 0.4
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_CRUISE 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_ALT_TC 2
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
param set-default FW_T_TAS_TC 2


param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5
param set-default NAV_LOITER_RAD 80

param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 0.75
param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_B_TRANS_DUR 8
param set-default VT_TYPE 2

set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom
